apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph-kubernetes.fullname" . }}
  labels:
    {{- include "graph-kubernetes.labels" . | nindent 4 }}
type: Opaque
data:
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
  jupiteroneIntegrationInstanceId: {{ default "" .Values.secrets.jupiteroneIntegrationInstanceId | b64enc | quote }}
